import { PrismaClient } from "@prisma/client";

const ACHIEVEMENTS = [
  {
    slug: "first_visit",
    name: "First Visit",
    description: "Eerste bezoek aan Doggy Beach House",
    icon: "🐾",
    ruleType: "VISIT_COUNT" as const,
    ruleConfig: { threshold: 1 },
    sortOrder: 1,
  },
  {
    slug: "beach_regular",
    name: "Beach Regular",
    description: "5 bezoeken",
    icon: "🏖️",
    ruleType: "VISIT_COUNT" as const,
    ruleConfig: { threshold: 5 },
    sortOrder: 2,
  },
  {
    slug: "doggy_beach_fan",
    name: "Doggy Beach Fan",
    description: "10 bezoeken",
    icon: "🌊",
    ruleType: "VISIT_COUNT" as const,
    ruleConfig: { threshold: 10 },
    sortOrder: 3,
  },
  {
    slug: "beach_legend",
    name: "Beach Legend",
    description: "25 bezoeken",
    icon: "👑",
    ruleType: "VISIT_COUNT" as const,
    ruleConfig: { threshold: 25 },
    sortOrder: 4,
  },
  {
    slug: "first_topup",
    name: "First Top-Up",
    description: "Eerste opwaardering",
    icon: "💳",
    ruleType: "TOP_UP_COUNT" as const,
    ruleConfig: { threshold: 1 },
    sortOrder: 10,
  },
  {
    slug: "wallet_lover",
    name: "Wallet Lover",
    description: "5 opwaarderingen",
    icon: "💖",
    ruleType: "TOP_UP_COUNT" as const,
    ruleConfig: { threshold: 5 },
    sortOrder: 11,
  },
  {
    slug: "big_spender",
    name: "Big Spender",
    description: "€100 totaal opgewaardeerd",
    icon: "💰",
    ruleType: "TOP_UP_TOTAL_EUR" as const,
    ruleConfig: { threshold: 100 },
    sortOrder: 12,
  },
  {
    slug: "receipt_rookie",
    name: "Receipt Rookie",
    description: "Eerste bon gescand",
    icon: "🧾",
    ruleType: "RECEIPT_COUNT" as const,
    ruleConfig: { threshold: 1 },
    sortOrder: 20,
  },
  {
    slug: "snack_lover",
    name: "Snack Lover",
    description: "10 snackproducten geregistreerd",
    icon: "🦴",
    ruleType: "PRODUCT_CATEGORY_COUNT" as const,
    ruleConfig: { threshold: 10, category: "SNACKS" },
    sortOrder: 21,
  },
  {
    slug: "licky_lover",
    name: "Licky Lover",
    description: "5 Licky-producten",
    icon: "🍦",
    ruleType: "PRODUCT_CATEGORY_COUNT" as const,
    ruleConfig: { threshold: 5, category: "LICKY" },
    sortOrder: 22,
  },
  {
    slug: "toy_collector",
    name: "Toy Collector",
    description: "5 speeltjes geregistreerd",
    icon: "🎾",
    ruleType: "PRODUCT_CATEGORY_COUNT" as const,
    ruleConfig: { threshold: 5, category: "TOYS" },
    sortOrder: 23,
  },
  {
    slug: "photo_pup",
    name: "Photo Pup",
    description: "Eerste foto-opdracht voltooid",
    icon: "📸",
    ruleType: "PHOTO_COUNT" as const,
    ruleConfig: { threshold: 1 },
    sortOrder: 30,
  },
];

export async function seedAchievements(prisma: PrismaClient) {
  for (const a of ACHIEVEMENTS) {
    await prisma.achievementDefinition.upsert({
      where: { slug: a.slug },
      create: a,
      update: {
        name: a.name,
        description: a.description,
        icon: a.icon,
        ruleType: a.ruleType,
        ruleConfig: a.ruleConfig,
        sortOrder: a.sortOrder,
      },
    });
  }
}
